kafka:
  bootstrap-servers: 127.0.0.1:9092
  topic.request-topic: requesttopic_users
  topic.requestreply-topic: replytopic_users
  consumergroup: requestreplygroup

spring:
  application:
    name: producer

  kafka:
    producer:
      max:
        request:
          size: 231072000
      batch-size: 60000000
      buffer-memory: 60000000
    bootstrap-servers: 127.0.0.1:9092
    client-id: producer
    consumer:
      group-id: requestreplygroup
      auto-offset-reset: earliest
      enable-auto-commit: false    
