<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_Kafka/SBConsumer/dbCriaPessoa" name="dbCriaPessoa-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="dbCriaPessoa.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_Kafka/SBConsumer/dbCriaPessoa"/>
    <wsdl:binding name="dbCriaPessoa_ptt-binding" type="dbc:dbCriaPessoa_ptt" xmlns:dbc="http://xmlns.oracle.com/pcbpel/adapter/db/OSB_Kafka/SBConsumer/dbCriaPessoa">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="dbCriaPessoa">
            <soap:operation soapAction="dbCriaPessoa"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>